#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if grep -q integrity-check /proc/cmdline; then
	plymouth quit || :
	casper-md5check /cdrom /cdrom/md5sum < /dev/tty1 > /dev/tty1
	reboot
	while :; do sleep 60; done
fi
