#!/bin/sh

PREREQ=""
DESCRIPTION="Adding live session user..."

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Add user
#tape,floppy,audio,video,usb,cdrom,netdev,dialout,wheel,sambashare,lp,lpadmin,plugdev,scanner
DEFAULT_GROUPS="floppy audio video wheel sambashare lp lpadmin scanner systemd-journal"
chroot /root /usr/sbin/useradd -m -s /bin/bash "$USERNAME"
for group in $DEFAULT_GROUPS; do
    chroot /root /usr/sbin/usermod -aG "$group" "$USERNAME"
done

# Edit password
# U6aMy0wojraho is blank password, but we choose empty password.
#chroot /root /bin/chmod +w /etc/shadow
#chroot /root /bin/sed -i '/^'"$USERNAME"':/s/!/U6aMy0wojraho/g' /etc/shadow
#chroot /root /bin/chmod 400 /etc/shadow
chroot /root /usr/bin/passwd -dq "$USERNAME"

#use chpasswd set passwd
#chroot /root usermod --password=$PASSWD $USER
#chroot /root chpasswd <<EOF
#$USER:$PASSWD
#EOF

# NOTE:
# This is required by osinstaller.
if [ -f /root/etc/sudoers ]; then
    echo "${USERNAME}  ALL=(ALL) NOPASSWD: ALL" >> /root/etc/sudoers
fi

log_end_msg
