#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up swap..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

devices=""
for device in /sys/block/[hs]d[a-z]/[hs]d[a-z][0-9]*; do
    if ! [ -b "/dev/${device##*/}" ]; then
        continue
    fi

    udevadm test-builtin blkid "$device" 2>/dev/null | grep -q "^ID_FS_USAGE=raid" && continue
    
    device="/dev/${device##*/}"

    magic=$(/bin/dd if="$device" bs=4086 skip=1 count=1 2>/dev/null | /bin/dd bs=10 count=1 2>/dev/null) || continue
    
    if [ "$magic" = "SWAPSPACE2" -o "$magic" = "SWAP-SPACE" ]; then
        # log "Found $device"
        devices="$devices $device"
    fi
done

for device in $devices; do
    cat >> $FSTAB <<EOF
$device swap swap defaults 0 0
EOF
done

log_end_msg
