#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login..."

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# lightdm
config='/root/etc/lightdm/lightdm.conf'
if [ -f $config ];then 
	sed -i 's/#autologin-user=/autologin-user='"$USERNAME"'/g' $config
	sed -i 's/#autologin-user-timeout=0/autologin-user-timeout=0/g' $config
fi

# gdm
config='/root/etc/gdm/custom.conf'
if [ -f $config ]; then
    for para in AutomaticLoginEnable \
                AutomaticLogin \
                TimedLoginEnable \
                TimedLoginDelay \
                TimedLogin; do
        if grep -q ^"$para"= $config; then
            sed -i '/^'"$para"'=/d' $config
        fi
    done
    sed -i -r \
        -e '/\[daemon\]/a#AutomaticLoginEnable=true' \
        -e '/\[daemon\]/a#AutomaticLogin='"$USERNAME"'' \
        -e '/\[daemon\]/a#TimedLoginEnable=true' \
        -e '/\[daemon\]/a#TimedLoginDelay=10' \
        -e '/\[daemon\]/a#TimedLogin='"$USERNAME"'' $config
fi

# kdm
config='/root/usr/share/config/kdm/kdmrc'
if [ -f $config ]; then
    sed -i -r \
        -e "s/^#AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#AutoLoginUser=.*\$/AutoLoginUser=$USERNAME/" \
        -e "s/^#AutoReLogin=.*\$/AutoReLogin=true/" \
	$config
fi

# lxdm
config='/root/etc/lxdm/lxdm.conf'
if [ -f $config ]; then
   sed -i -r \
        -e "s/^# autologin=dgod/autologin=$USERNAME/" \
        -e "s/^# session/session/" \
	$config
fi

log_end_msg
