#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login..."

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# lightdm
if [ -f /root/etc/lightdm/lightdm.conf ];then 
	CustomFile=/root/etc/lightdm/lightdm.conf
	sed -i 's/#autologin-user=/autologin-user='"$USERNAME"'/g' $CustomFile
	sed -i 's/#autologin-user-timeout=0/autologin-user-timeout=0/g' $CustomFile
fi

# gdm
if [ -f /root/etc/gdm/custom.conf ]; then
    GDMCustomFile=/root/etc/gdm/custom.conf
    for para in AutomaticLoginEnable \
                AutomaticLogin \
                TimedLoginEnable \
                TimedLoginDelay \
                TimedLogin; do
        if grep -q ^"$para"= $GDMCustomFile; then
            sed -i '/^'"$para"'=/d' $GDMCustomFile
        fi
    done
    sed -i -r \
        -e '/\[daemon\]/a#AutomaticLoginEnable=true' \
        -e '/\[daemon\]/a#AutomaticLogin='"$USERNAME"'' \
        -e '/\[daemon\]/a#TimedLoginEnable=true' \
        -e '/\[daemon\]/a#TimedLoginDelay=10' \
        -e '/\[daemon\]/a#TimedLogin='"$USERNAME"'' $GDMCustomFile	
fi

# kdm
if [ -f /root/etc/kde4/kdm/kdmrc ]; then
    sed -i -r \
        -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$USERNAME/" \
        -e "s/^#?AutoReLogin=.*\$/AutoReLogin=true/" \
        /root/etc/kde4/kdm/kdmrc
fi

# lxdm
if [ -f /root/etc/lxdm/lxdm.conf ]; then
   sed -i -r \
        -e "s/^# autologin=dgod/autologin=$USERNAME/" \
        -e "s/^# session/session/" \
        /root/etc/lxdm/lxdm.conf
fi

log_end_msg
