#! /bin/sh

PREREQ=""
DESCRIPTION="Preconfiguring /etc/modules..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

case "$DPKG_ARCH" in
# load the right modules
powerpc|ppc64)
	for file in /root/etc/modules /root/etc/modules-load.d/modules.conf; do
		[ -f "$file" ] && echo snd_powermac >> "$file"
	done
	;;
esac

log_end_msg
