#!/bin/sh
#

PREREQ=""
DESCRIPTION="Enable livecd installer..."

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	# get pre-requisites
	prereqs)
		prereqs
		exit 0
	        ;;
esac

. /scripts/casper-functions

file=osinstaller.service

for x in $(cat /proc/cmdline); do
	case $x in 
	install-automatic|install-nodesktop)
		chroot /root /usr/bin/systemctl enable $file
		break ;;
	*)
		chroot /root /usr/bin/systemctl disable $file
	esac

done

# End of file

