#!/bin/sh

PREREQ=""
DESCRIPTION="Searching filesystem.size file..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

sizefile=/root/cdrom/casper/filesystem.size

if [ -e "$sizefile" ]; then
	cat $sizefile >/root/etc/filesystem.size
fi

log_end_msg
