#!/bin/sh

PREREQ=""
DESCRIPTION="StartOS misc tools..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

sizefile="/root/cdrom/.disk/size"
datefile="/root/cdrom/.disk/date"

if [ -e "$sizefile" ]; then
	cat "$sizefile" >/root/etc/filesystem.size
fi

if [ -e "$datefile" ]; then
	cat "$datefile" >/root/etc/build.date
fi

log_end_msg
