#! /bin/sh

PREREQ=""
DESCRIPTION="Setting up locales..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -e /root/etc/default/locale ]; then
    grep_file=/root/etc/default/locale
elif [ -e /root/etc/environment ]; then # Old locales policy
    grep_file=/root/etc/environment
fi

if [ -n "${grep_file}" ]; then
    # use rootfs configured locale
    locale=$(grep -s 'LANG=' ${grep_file} | sed s/'LANG='// | tr -d '"' )
fi

# commandline
for x in $(cat /proc/cmdline); do
    case $x in
	locale=*)
	    locale=${x#locale=}
	    set_locale="true"
	    break ;;
    esac
done

if [ -z "${locale}" ]; then
    # Default value
    locale=zh_CN.UTF-8
    set_locale="true"
fi

if [ "${set_locale}" ]; then
    LANG=$(grep "^${locale}" /root/usr/share/i18n/SUPPORTED | grep UTF-8 |sed -e 's, .*,,' -e q)
    printf 'LANG="%s"\n' "${LANG}" > /root/etc/default/locale
    printf 'LANG="%s"\n' "${LANG}" >> /root/etc/environment
    printf '%s UTF-8\n' "${LANG}" > /root/etc/locale.gen
    chroot /root /usr/sbin/locale-gen "${LANG}"
    #
    case ${LANG%%.*} in
            zh_TW|zh_tw)
		    timez="Asia/Taipei"
		    LANGUAGE='"zh_TW:zh"' ;;
	    zh_HK|zh_hk)
		    timez="Asia/Hong_Kong"
		     LANGUAGE='"zh_HK:zh"' ;;
	     en_US|en_us)
	              timez="UTC"
	              LANGUAGE='"en_US:en"'  ;;
	    zh_CN|zh_cn|*)
	               timez="Asia/Shanghai"
	               LANGUAGE='"zh_CN:zh"' 
     esac
     printf 'LANGUAGE="%s"\n' "${LANGUAGE}" >> /root/etc/default/locale
     if [ -f /root/usr/share/zoneinfo/${timez} ]; then
     	     [ -h /root/etc/localtime ] && rm -f /root/etc/localtime
	     cat /root/usr/share/zoneinfo/${timez}  >/root/etc/localtime
 	     echo ${timez}                          >/root/etc/timezone	
     fi
fi

# Creat well known users dirs, depends on locale
if [ -x /root/usr/bin/xdg-user-dirs-update ];then
	. /etc/casper.conf
	chroot /root su "$USERNAME" -c "/usr/bin/xdg-user-dirs-update"
fi

log_end_msg
