#!/bin/sh

PREREQ=""
DESCRIPTION="Misc settings for Ylmf_OS, timezone locales..."

prereqs() {
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# parse comdline
for x in $(cat /proc/cmdline); do
	case $x in
	locale=*)	
		locale=${x#locale=}
		break ;;
               *) continue
	esac
done
ROOT="/root"
case ${locale%%.*} in 
	zh_TW|zh_tw)
		timez="Asia/Taipei"
		LANG='"zh_TW.UTF-8"'
		LANGUAGE='"zh_TW:zh"'
			;;
	zh_HK|zh_hk)
		timez="Asia/Hong_Kong"
		LANG='"zh_HK.UTF-8"'
		LANGUAGE='"zh_HK:zh"'
			;;
	en_US|en_us)
		timez="UTC"
		LANG='"en_US.UTF-8"'
		LANGUAGE='"en_US:en"'
			;;
	zh_CN|zh_cn|*)
		timez="Asia/Shanghai"
		LANG='"zh_CN.UTF-8"'
		LANGUAGE='"zh_CN:zh"'
			;;
esac

if cd "$ROOT"; then
	echo LANG=${LANG} 	   	   >etc/default/locale 
	echo LANGUAGE=${LANGUAGE}	   >>etc/default/locale 
	[ -h etc/localtime ] && rm etc/localtime
	cat usr/share/zoneinfo/${timez}    >etc/localtime
	echo ${timez}   		   >etc/timezone
fi		

log_end_msg
