#!/bin/sh
#

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	# get pre-requisites
	prereqs)
		prereqs
		exit 0
	        ;;
esac

. /scripts/casper-functions

for x in $(cat /proc/cmdline); do
	case $x in 
	install-automatic|install-nodesktop)
		log_begin_msg "Enable Ylmf_OS livecd installer..."
		chroot /root /bin/systemctl enable osinstaller.service 
		break ;;
	*)
		chroot /root /bin/systemctl disable osinstaller.service 
	esac

done

# End of file

