#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Author: Zhongxin Huang <zhongxin.huang@gmail.com>
#

import os
import sys


def main():
    ''' '''
    with open('/proc/cmdline', 'r') as f:
        cmdline = f.readline()
        if 'boot=casper' in cmdline:
            # Time before session is considered idle
            os.system('/usr/bin/gsettings set org.gnome.desktop.session idle-delay 0')
            # Dim the screen after a period of inactivity
            os.system('/usr/bin/gsettings set org.gnome.settings-daemon.plugins.power idle-dim false')

if __name__ == '__main__':
    main()
